### ISSUE TITLE
Theme does not go to dark mode

### ISSUE THREAD

**Issue by kaizersoje** [einschmidt/github_dark_theme#4]
I have noticed the theme does not go to dark mode when in Auto mode.

![image](https://user-images.githubusercontent.com/54566217/161504165-6d185651-0a0a-4320-b8b6-b7e2890ca82e.png)

When I change the mode to Dark, then the theme changes.

![image](https://user-images.githubusercontent.com/54566217/161504275-53129876-923c-4907-9296-83c5a4730ce8.png)

**Comment by einschmidt** [comment]
Hi @kaizersoje ,
Thanks for reaching out.
Unfortunately, I wasn't able to reproduce your finding.
What you _could_ try:

1. Reload Themes
2. Restart Home Assistant

If that doesn't help, please can you send me the first few lines of code from your theme file in your theme folder?

**Comment by einschmidt** [comment]
**Update**
Hi @kaizersoje ,

Reading through the home assistant rules for themes, it seems you ran into a bug.

The theme has been created to hold a `dark mode` only. In this case, a theme should behave like this:

```
By using the new modes key plus the subkey dark this theme will now be based on the default dark theme. The final theme rules are determined in three steps: First, the default dark theme CSS variables will be applied, then second the CSS variables from the top level of the theme that are mode-independent (primary-color: steelblue in this example) and lastly the mode-specific CSS variables will be layered on top (secondary-text-color: slategray).

Note: Since this example theme only has a dark mode defined, this mode will automatically be used.
```
https://www.home-assistant.io/integrations/frontend/#dark-mode-support

However, instead of showing the dark mode on Auto, it uses the light mode when your system is configured to show the light mode.

The quick workaround is to set your config to `Dark`. Otherwise, you could leave `Auto` but change your OS settings to dark.

If none of that is acceptable, you could still create a copy of the theme without the automatic Dark mode.

Let me know in case you have further questions.

**Comment by kaizersoje** [comment]
It's quite funny what's happening. I am trying to set the theme using the `frontend.set_theme` service.

```
service: frontend.set_theme
data:
  mode: dark
  name: Github Dark Theme
```

Unfortunately, the theme is not being set by calling the service. However, I can set the theme from the Profile page.

**Comment by einschmidt** [comment]
For the service `frontend.set_theme` to work you must select `Backend-selected` on the profile page.

One of those tiny things only a few people tell you. ;-)

**Comment by kaizersoje** [comment]
That's something I didn't know. :)

**Comment by kaizersoje** [comment]
I have got `Backend-selected` on my profile page.

![image](https://user-images.githubusercontent.com/54566217/162336121-65c1dc9f-f215-46ef-a91d-be5a51249465.png)

Calling the service still does nothing.

```
service: frontend.set_theme
data:
  mode: dark
  name: Github Dark Theme
```

**Comment by einschmidt** [comment]
I can confirm your finding, although only when also my OS color scheme is set to `Light`.

Once I set my OS color scheme to `Dark`, it works as expected.

Again, I assume this is a bug in Home Assistant.

**Comment by kaizersoje** [comment]
Ok I'll raise an issue with home_assistant/frontend.

**Comment by kaizersoje** [comment]
I have raised issue #[12260](https://github.com/home-assistant/frontend/issues/12260)

**Comment by einschmidt** [comment]
Thank you very much! I have added further information. Let's wait for a response.

**Comment by kaizersoje** [comment]
I removed `dark` mode from the [code ](https://github.com/kaizersoje/github_dark_theme/blob/main/themes/github_dark_theme.yaml)and it seems to be working as expected.

**Comment by einschmidt** [comment]
Let me try something. Will post the findings here soon.

**Comment by einschmidt** [comment]
Please check the next release again. :-)
