### ISSUE TITLE
Unable to see text in a text field

### ISSUE THREAD

**Issue by kaizersoje** [einschmidt/github_dark_theme#5]
![image](https://user-images.githubusercontent.com/54566217/166920571-47b441bd-68cb-4c3a-90dc-df8ea811be0c.png)

Not able to figure out which variable needs to be updated. The label is not legible when the field is not selected.

![image](https://user-images.githubusercontent.com/54566217/166920731-d6739f07-a5e4-4d69-89a1-ac7639042d9c.png)

**Comment by kaizersoje** [comment]
Am I missing something?

**Comment by einschmidt** [comment]
Duplicate of #4
