### ISSUE TITLE
Card's box-shadow is rendered unevenly in firefox with fractional scaling

### ISSUE THREAD

**Issue by monte-monte** [einschmidt/github_dark_theme#8]
I have HiDPI screen and use fractional scaling in Firefox. I guess it's the reason of the issue i had with this theme, before I made a simple change:
![github_theme_issue_compare](https://github.com/einschmidt/github_dark_theme/assets/6649967/ac769a6c-d04b-47f4-8970-32e0ada1d22b)
(I wish github wouldn't compress this bad, but I hope you can see the problem)
Switching box shadow from 1px to 0.1rem fixes the thin contour on the left and the top of the card. Overall shadow size remains the same. The only problem is that it is scaling with the page being scaled. But for me it's still better then uneven outline.
https://github.com/einschmidt/github_dark_theme/blob/2a8c4cea9e1bcb17b013cadea758ef147c235838/themes/github_dark_theme.yaml#L52C24-L52C47

**Comment by monte-monte** [comment]
Checked on my phone, seems that 0.08 rem is closer to 1px, on the PC both (0.08 an 0.1) looks identical.

**Comment by einschmidt** [comment]
Hi @monte-monte 

Thank you very much for making aware of the issue.

Can you do me a favour and try this updated theme file in your setup? Just replace the full theme file with the below one.

https://github.com/einschmidt/github_dark_theme/blob/switch-px-to-rem/themes/github_dark_theme.yaml

Upon your feedback I will merge the changes.

Thanks.

**Comment by monte-monte** [comment]
@einschmidt yes, that's working for me.
